project_id = "rueaxiyvseaxkysnoock"

[functions.create-deposit-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.rent-strategy]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false

[functions.record-profit-fee]
verify_jwt = false