/**
 * AIQTP Platform Fee Structure
 * 
 * Revenue Model: Free platform access, fees only on realized profits
 * $0 to initiate, $20 minimum investment
 * Gas/transfer fees applied separately
 */

// Performance royalty — tier chosen by % gain realized on each closed trade
// (gain ÷ cost basis). Mirrors DB function public.performance_royalty_rate.
// min/max are gain percentages.
export const PROFIT_TIERS = [
  { min: 0.01, max: 10, rate: 0.05, label: "5%" },
  { min: 10.01, max: 100, rate: 0.03, label: "3%" },
  { min: 100.01, max: 1000, rate: 0.01, label: "1%" },
  { min: 1000.01, max: Infinity, rate: 0.001, label: "0.10%" },
] as const;

// Minimum investment requirement
export const MIN_INVESTMENT = 20;

export function royaltyRateForGainPct(gainPct: number): number {
  if (!(gainPct > 0)) return 0;
  if (gainPct <= 10) return 0.05;
  if (gainPct <= 100) return 0.03;
  if (gainPct <= 1000) return 0.01;
  return 0.001;
}

// Calculate royalty for a realized gain given its cost basis
export function calculatePlatformFee(
  profitAmount: number,
  costBasis: number,
): { fee: number; rate: number; tierLabel: string; gainPct: number } {
  if (profitAmount <= 0 || costBasis <= 0) {
    return { fee: 0, rate: 0, tierLabel: "No charge (no profit)", gainPct: 0 };
  }
  const gainPct = (profitAmount / costBasis) * 100;
  const rate = royaltyRateForGainPct(gainPct);
  const tier = PROFIT_TIERS.find((t) => t.rate === rate);
  return { fee: Math.round(profitAmount * rate * 100) / 100, rate, tierLabel: tier?.label ?? "0%", gainPct };
}

// NFT Marketplace fees - competitive with OpenSea (2.5%), LooksRare (2%), Blur (0.5%)
export const NFT_FEES = {
  listingFee: 0, // $0 to list
  saleFee: 0.02, // 2% on sale (matching/beating competition)
  royaltyMax: 0.10, // 10% max creator royalty support
  comparison: [
    { platform: "OpenSea", fee: "2.5%" },
    { platform: "LooksRare", fee: "2%" },
    { platform: "Blur", fee: "0.5%" },
    { platform: "AIQTP", fee: "2%", highlight: true },
  ]
} as const;

// Strategy/Bot Marketplace - profit sharing model for graduated bots
// Bots achieving 80%+ profitability qualify for marketplace review
export const STRATEGY_FEES = {
  listingFee: 0, // $0 to list
  graduationThreshold: 75, // 75% profitability required (lowered from 80)
  consistencyThreshold: 69.9, // 69.9% consistency (lowered from 70)
  minBacktestCount: 4, // lowered from 5 to widen the funnel
  defaultMonthlyRentalPrice: 99,
  profitShare: {
    creator: 0.50, // 50% lifetime share to strategy creator
    platform: 0.50, // 50% to platform
  },
  // Creator gets 25% of ALL profits generated by their bot forever
  eliteClubPerks: ['exclusive_chat', 'priority_testing', 'creator_badge', 'early_features'],
} as const;

// Real Estate / Tokenized Property
export const REAL_ESTATE_FEES = {
  listingFee: 0, // $0 to list
  transactionFee: 0.01, // 1% finder's fee (industry: 3-6%)
  // Higher value = lower tier kicks in
  comparison: [
    { platform: "Traditional Broker", fee: "3-6%" },
    { platform: "RealT", fee: "2%" },
    { platform: "AIQTP", fee: "1%", highlight: true },
  ]
} as const;

// Collectibles (Trading Cards, Memorabilia)
// Uses tiered profit model - 9%/6%/3%/1%
export const COLLECTIBLES_FEES = {
  listingFee: 0,
  saleFee: "tiered", // Uses PROFIT_TIERS
  authenticationFee: 0, // Included free
  comparison: [
    { platform: "eBay", fee: "12.9-15%" },
    { platform: "COMC", fee: "10-20%" },
    { platform: "StockX", fee: "8-12%" },
    { platform: "AIQTP", fee: "1-9%", highlight: true },
  ]
} as const;

// Precious Metals
export const PRECIOUS_METALS_FEES = {
  listingFee: 0,
  spreadFee: 0.015, // 1.5% spread (industry: 2-5%)
  storageFee: 0, // No storage fee for first year
  comparison: [
    { platform: "JM Bullion", fee: "2-4% spread" },
    { platform: "APMEX", fee: "3-5% spread" },
    { platform: "AIQTP", fee: "1.5% spread", highlight: true },
  ]
} as const;

// Luxury Goods (Watches, Wine, Art)
export const LUXURY_FEES = {
  listingFee: 0,
  saleFee: "tiered", // Uses PROFIT_TIERS
  authenticationFee: 0, // Included
  insuranceFee: "included", // Included in sale
  comparison: [
    { platform: "Christie's", fee: "25% buyer premium" },
    { platform: "1stDibs", fee: "15-20%" },
    { platform: "Sotheby's", fee: "20-25%" },
    { platform: "AIQTP", fee: "1-9%", highlight: true },
  ]
} as const;

// Virtual Assets (Gaming, Metaverse)
export const VIRTUAL_ASSETS_FEES = {
  listingFee: 0,
  saleFee: 0.025, // 2.5% flat
  comparison: [
    { platform: "Steam Market", fee: "15%" },
    { platform: "G2G", fee: "5-10%" },
    { platform: "AIQTP", fee: "2.5%", highlight: true },
  ]
} as const;

// Affiliate/Referral Program - Tiered by referral count
// Referrer earns % of PLATFORM'S earnings from their referrals
export const AFFILIATE_FEES = {
  baseTier: { minReferrals: 0, rate: 0.10, label: "10%" }, // Base: 10% of platform's cut
  tierBonuses: [
    { minReferrals: 10, rate: 0.15, label: "15%" }, // 10+ referrals: 15%
    { minReferrals: 50, rate: 0.20, label: "20%" }, // 50+ referrals: 20%
    { minReferrals: 100, rate: 0.25, label: "25%" }, // 100+ referrals: 25%
  ],
  lifetimeReferral: true, // Lifetime earnings from referrals
  example: {
    referredUserProfit: 5000,
    platformFee: 150, // $5,000 gain on $50,000 basis = 10% gain → 5% royalty = $250; on $10,000 basis = 50% → 3% = $150
    referrerEarnings: {
      base: 15, // 10% of $150
      tier10: 22.50, // 15% of $150
      tier50: 30, // 20% of $150
      tier100: 37.50, // 25% of $150
    }
  }
} as const;

// Calculate affiliate earnings based on referral count
export function calculateAffiliateEarnings(
  platformFeeAmount: number, 
  referralCount: number
): { earnings: number; rate: number; tierLabel: string } {
  let rate: number = AFFILIATE_FEES.baseTier.rate;
  let tierLabel: string = AFFILIATE_FEES.baseTier.label;
  
  for (const tier of AFFILIATE_FEES.tierBonuses) {
    if (referralCount >= tier.minReferrals) {
      rate = tier.rate;
      tierLabel = tier.label;
    }
  }
  
  return {
    earnings: platformFeeAmount * rate,
    rate,
    tierLabel
  };
}

// Summary for display
export const FEE_SUMMARY = {
  headline: "Free to Start. Pay Only on Profits.",
  subheadline: "$0 platform fee • $0 strategy agents • Royalty only on realized gains",
  tiers: [
    { range: "0.01% – 10% gain", rate: "5% of profit" },
    { range: "10.01% – 100% gain", rate: "3% of profit" },
    { range: "100.01% – 1,000% gain", rate: "1% of profit" },
    { range: "1,000.01%+ gain", rate: "0.10% of profit" },
  ],
  additionalCosts: [
    "Gas fees (network dependent)",
    "Transfer/withdrawal fees (at cost)",
    "Third-party authentication (if applicable)",
  ],
  freeIncludes: [
    "Full platform access",
    "All trading tools",
    "AI predictions",
    "Backtesting",
    "Strategy builder",
    "Portfolio analytics",
    "Educational content",
  ]
} as const;

// Helper to format fee comparison
export function formatFeeComparison(fees: readonly { platform: string; fee: string; highlight?: boolean }[]) {
  return fees.map(f => ({
    ...f,
    isBest: f.highlight === true
  }));
}

// ============================================
// LEGAL DISCLAIMERS & RISK WARNINGS
// ============================================

export const LEGAL_DISCLAIMERS = {
  // Main risk warning
  riskWarning: `
RISK WARNING: Trading cryptocurrencies, digital assets, NFTs, and other financial instruments involves substantial risk of loss and is not suitable for all investors. The high degree of leverage can work against you as well as for you. Before deciding to trade, you should carefully consider your investment objectives, level of experience, and risk appetite. The possibility exists that you could sustain a loss of some or all of your initial investment and therefore you should not invest money that you cannot afford to lose.
  `.trim(),

  // Not financial advice
  notFinancialAdvice: `
NOT FINANCIAL ADVICE: AIQTP and its affiliates do not provide investment, legal, or tax advice. All content, tools, strategies, predictions, and information provided on this platform are for informational and educational purposes only. Nothing on this platform constitutes a recommendation to buy, sell, or hold any cryptocurrency, security, or other asset. Always conduct your own research and consult with qualified professionals before making any financial decisions.
  `.trim(),

  // Not a broker/adviser
  notBrokerAdviser: `
NOT A BROKER OR INVESTMENT ADVISER: AIQTP is a technology platform that provides tools and services. We are not a registered broker-dealer, investment adviser, or financial institution. We do not manage client funds, execute trades on behalf of users, or provide personalized investment recommendations. Users are solely responsible for their own trading decisions and actions.
  `.trim(),

  // No guarantees
  noGuarantees: `
NO GUARANTEES: Past performance is not indicative of future results. AI predictions, backtesting results, strategy performance metrics, and any other projections or analyses are provided for informational purposes only and do not guarantee future performance. All trading strategies carry risk, and there is no assurance that any strategy will be profitable.
  `.trim(),

  // Visual purposes disclaimer
  visualPurposes: `
VISUAL PURPOSES ONLY: All images, charts, graphs, mockups, screenshots, and visual representations on this platform are for illustrative and educational purposes only. They do not represent actual trading results, guaranteed outcomes, or real portfolio performance unless explicitly stated otherwise. Demo accounts and simulated trading do not reflect actual market conditions.
  `.trim(),

  // Fee disclaimer
  feeDisclaimer: `
FEE NOTICE: All fees, rates, and pricing displayed are subject to change without notice. Actual costs may vary based on network conditions, gas fees, exchange rates, third-party service providers, and other factors beyond our control. Users are responsible for verifying all applicable fees before executing transactions. Minimum investment amounts and fee structures are subject to adjustment based on market conditions and regulatory requirements.
  `.trim(),

  // Third-party disclaimer
  thirdPartyDisclaimer: `
THIRD-PARTY SERVICES: This platform may integrate with third-party services, exchanges, wallets, and APIs. AIQTP is not responsible for the actions, security, or reliability of third-party services. Users should review and accept the terms of service for any third-party integrations they choose to use.
  `.trim(),

  // Regulatory compliance
  regulatoryCompliance: `
REGULATORY NOTICE: Cryptocurrency and digital asset regulations vary by jurisdiction. It is your responsibility to ensure compliance with all applicable laws and regulations in your jurisdiction. Some features or services may not be available in certain regions due to regulatory restrictions. AIQTP reserves the right to restrict access to services based on geographic location.
  `.trim(),

  // Loss of funds
  lossOfFunds: `
POTENTIAL LOSS OF FUNDS: You acknowledge and accept that there is a risk of losing some or all of your invested capital. This includes but is not limited to: market volatility, technical failures, smart contract vulnerabilities, exchange failures, regulatory changes, hacking, and human error. Never invest more than you can afford to lose.
  `.trim(),

  // AI disclaimer
  aiDisclaimer: `
AI & ALGORITHM DISCLAIMER: AI-powered predictions, automated trading strategies, and algorithmic tools are experimental technologies. They may produce inaccurate predictions, execute trades at unfavorable prices, or fail to operate as expected. Users should monitor all automated systems and maintain the ability to intervene manually. AI predictions should be used as one of many inputs in your decision-making process, not as the sole basis for trading decisions.
  `.trim(),

  // Affiliate disclaimer
  affiliateDisclaimer: `
AFFILIATE PROGRAM: Referral bonuses and affiliate earnings are calculated based on the platform's actual fee collections from referred users. Earnings are subject to the platform's fee collection, user activity, and program terms. The platform reserves the right to modify, suspend, or terminate the affiliate program at any time. Affiliate earnings may be subject to applicable taxes in your jurisdiction.
  `.trim(),

  // Data accuracy
  dataAccuracy: `
DATA ACCURACY: While we strive to provide accurate and timely information, we do not warrant the accuracy, completeness, or reliability of any data, prices, charts, or information displayed on this platform. Data may be delayed, contain errors, or become outdated. Always verify information from multiple sources before making trading decisions.
  `.trim(),

  // Full legal footer
  fullDisclaimer: `
© ${new Date().getFullYear()} AIQTP™ AI Quantum Trading Portal. All rights reserved. AIQTP™ is a registered trademark of TRUST AIQTP HOLDINGS (TAH), a Wyoming trust entity. Platform technology and intellectual property are operated under exclusive license by AIQTP TRUST ENTERPRISE (ATE), New Jersey. By using this platform, you acknowledge that you have read, understood, and agree to be bound by our Terms of Service, Privacy Policy, and all applicable disclaimers. This platform is provided "as is" without warranties of any kind, either express or implied. AIQTP, its officers, directors, employees, agents, and affiliates shall not be liable for any damages arising from the use of this platform or reliance on any information provided herein. Trading involves substantial risk. Only risk capital should be used for trading. Past performance is not indicative of future results.
  `.trim(),
  // Force Majeure / Acts of God
  forceMajeure: `
FORCE MAJEURE & ACTS OF GOD: AIQTP shall not be liable for any failure or delay in performance resulting from events beyond our reasonable control, including but not limited to: natural disasters, earthquakes, floods, hurricanes, tornadoes, tsunamis; solar flares, geomagnetic storms, or electromagnetic pulse (EMP) events; acts of war, terrorism, civil unrest, insurrection, or government sanctions; epidemics, pandemics, or public health emergencies; power outages, blackouts, or utility failures; internet service disruptions, DNS failures, or telecommunications outages; cyberattacks, ransomware, distributed denial-of-service (DDoS) attacks, or zero-day exploits; regulatory actions, exchange halts, market circuit breakers, or government-mandated trading suspensions; data center failures, cloud provider outages, or hardware malfunctions; strikes, labor disputes, or supply chain disruptions; any other event that could not have been reasonably foreseen or prevented. In such events, affected obligations shall be suspended for the duration of the force majeure event. Users acknowledge and accept these risks as inherent to digital financial services.
  `.trim(),

  // Limitation of Liability
  limitationOfLiability: `
LIMITATION OF LIABILITY: TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AIQTP, ITS PARENT ENTITIES (TRUST AIQTP HOLDINGS), SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, AND SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, DATA, OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (a) YOUR USE OF OR INABILITY TO USE THE PLATFORM; (b) ANY UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA; (c) ANY THIRD-PARTY CONDUCT ON THE PLATFORM; (d) TRADING LOSSES, MISSED TRADES, OR ERRONEOUS EXECUTIONS; (e) SYSTEM OUTAGES, MAINTENANCE PERIODS, OR TECHNICAL FAILURES; (f) ERRORS IN AI PREDICTIONS, ALGORITHMIC STRATEGIES, OR AUTOMATED TRADING SYSTEMS; (g) EXCHANGE DELISTINGS, SMART CONTRACT FAILURES, OR BLOCKCHAIN NETWORK ISSUES. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE FEES ACTUALLY PAID BY YOU TO AIQTP IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
  `.trim(),

  // Assumption of Risk & Waiver
  assumptionOfRisk: `
ASSUMPTION OF RISK & WAIVER: BY USING THIS PLATFORM, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT: (1) Trading digital assets, cryptocurrencies, derivatives, and financial instruments carries inherent and substantial risks including total loss of capital; (2) You are solely responsible for all trading decisions and outcomes; (3) Historical exchange failures (including but not limited to Mt. Gox, FTX, Knight Capital, Robinhood outages, CME disruptions, NYSE glitches) demonstrate systemic risks inherent to financial platforms; (4) No platform, technology, or security measure can guarantee 100% uptime, protection against all cyber threats, or prevention of all losses; (5) You voluntarily assume all risks associated with your use of this platform; (6) You waive, release, and discharge AIQTP from any and all claims, demands, and causes of action arising from unforeseeable events, system failures, or market conditions beyond our control; (7) This waiver applies to known and unknown risks, foreseen and unforeseen events.
  `.trim(),

  // Insurance & Asset Protection Notice
  insuranceNotice: `
INSURANCE & ASSET PROTECTION: AIQTP maintains commercially reasonable cyber liability insurance, errors & omissions (E&O) coverage, and operational risk policies to protect platform operations. However, these policies do not directly cover individual user trading losses, market-related losses, or losses resulting from user error. Users are strongly encouraged to: (a) Maintain their own investment insurance and asset protection coverage; (b) Diversify holdings across multiple platforms and custodians; (c) Use hardware wallets for long-term storage; (d) Set appropriate stop-loss parameters; (e) Never invest funds needed for essential expenses. AIQTP may offer optional asset protection plans and insurance products through third-party providers — these are separate products with their own terms and coverage limits. AIQTP does not guarantee or underwrite any third-party insurance products.
  `.trim(),

  // Data Breach Notification
  dataBreachNotice: `
DATA BREACH PROTOCOL: In the event of a confirmed data breach affecting user information, AIQTP will: (1) Notify affected users within 72 hours of discovery as required by applicable regulations (GDPR, CCPA, state breach notification laws); (2) Provide details of the nature and scope of the breach; (3) Outline steps taken to contain and remediate the breach; (4) Offer guidance on protective measures users should take; (5) Cooperate with relevant regulatory authorities and law enforcement. Users are responsible for maintaining strong, unique passwords and enabling two-factor authentication.
  `.trim(),

  // System Availability SLA
  systemAvailability: `
SYSTEM AVAILABILITY: AIQTP targets 99.9% uptime for core services but does not guarantee uninterrupted access. Scheduled maintenance windows will be announced in advance when possible. During periods of extreme market volatility, certain features may be temporarily restricted to protect system integrity and user interests. Historical events such as the Robinhood March 2020 outage ($9.9M settlement), CME November 2025 data center failure, and NYSE January 2023 glitch ($9M SEC fine) demonstrate that even the largest exchanges experience downtime. Users should maintain alternative access to markets and should not rely solely on any single platform.
  `.trim(),
} as const;

// Compact disclaimers for UI badges/banners
export const COMPACT_DISCLAIMERS = {
  risk: "⚠️ Trading involves substantial risk of loss",
  notAdvice: "📋 Not financial advice",
  noGuarantee: "🎯 Past performance ≠ future results",
  visualOnly: "🖼️ Images for illustration only",
  feesVary: "💰 Fees subject to change & actual costs",
  aiExperimental: "🤖 AI predictions are experimental",
  dyor: "🔍 Always do your own research",
} as const;

// Required acknowledgment for onboarding
export const REQUIRED_ACKNOWLEDGMENTS = [
  "I understand that trading involves substantial risk of loss",
  "I acknowledge that AIQTP does not provide financial advice",
  "I understand that past performance does not guarantee future results",
  "I accept that all fees are subject to actual network costs",
  "I confirm I am trading with funds I can afford to lose",
  "I understand AI predictions are experimental and not guaranteed",
  "I acknowledge force majeure events (natural disasters, cyberattacks, solar flares, government actions) may disrupt services and AIQTP is not liable for losses during such events",
  "I waive the right to hold AIQTP liable for unforeseeable conditions, acts of god, or system failures beyond reasonable control",
  "I understand that no platform can guarantee 100% uptime or absolute security",
  "I agree to the Terms of Service, Privacy Policy, and Risk Disclosures",
] as const;
