/**
 * Extended EIP Standards — Infrastructure & Protocol Level
 * Sourced from https://eips.ethereum.org/ and https://github.com/ethereum/EIPs
 */

import type { ProtocolStandard } from './protocolRegistry';

export const EXTENDED_EIP_STANDARDS: ProtocolStandard[] = [
  // ── Core Infrastructure ──
  {
    id: 'eip-165',
    category: 'eip',
    number: '165',
    name: 'EIP-165: Standard Interface Detection',
    description: 'Defines a method to publish and detect which interfaces a smart contract implements. All ERC token contracts MUST implement EIP-165 to declare support for ERC-20, ERC-721, ERC-1155, etc. Foundation for contract interoperability.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-165',
    applicableTo: ['All smart contracts', 'Interface detection', 'Interoperability'],
    requiredForCompliance: true,
    relatedStandards: ['erc-721', 'erc-1155', 'eip-2981'],
  },
  {
    id: 'eip-173',
    category: 'eip',
    number: '173',
    name: 'EIP-173: Contract Ownership Standard',
    description: 'Standardizes an owner() function and OwnershipTransferred event for smart contracts. Defines who controls admin functions. OpenZeppelin\'s Ownable contract implements this standard.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-173',
    applicableTo: ['Contract ownership', 'Admin functions', 'Governance'],
    requiredForCompliance: true,
    relatedStandards: ['oz-access-control', 'erc-20', 'erc-721'],
  },
  {
    id: 'eip-712',
    category: 'eip',
    number: '712',
    name: 'EIP-712: Typed Structured Data Signing',
    description: 'Standard for hashing and signing typed structured data (not just bytestrings). Enables human-readable signing in wallets — users see exactly what they\'re signing. Required for ERC-2612 Permit, meta-transactions, and gasless approvals.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-712',
    applicableTo: ['Wallet signing', 'Meta-transactions', 'Permit approvals', 'Order signing'],
    requiredForCompliance: true,
    relatedStandards: ['erc-2612', 'eip-191', 'erc-20'],
  },
  {
    id: 'eip-191',
    category: 'eip',
    number: '191',
    name: 'EIP-191: Signed Data Standard',
    description: 'Defines a format for signed data in Ethereum, preventing cross-contract replay attacks. Prefixes signed messages with version bytes. Foundation for all off-chain signature verification.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-191',
    applicableTo: ['Message signing', 'Off-chain verification', 'Authentication'],
    requiredForCompliance: true,
    relatedStandards: ['eip-712', 'eip-1271'],
  },
  {
    id: 'eip-1271',
    category: 'eip',
    number: '1271',
    name: 'EIP-1271: Contract Signature Validation',
    description: 'Standard for validating signatures from smart contract wallets (not just EOAs). Enables multi-sig wallets, smart accounts, and account abstraction to sign and verify messages. Critical for institutional custody.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1271',
    applicableTo: ['Smart wallets', 'Multi-sig', 'Account abstraction', 'Institutional custody'],
    requiredForCompliance: false,
    relatedStandards: ['eip-191', 'eip-712', 'eip-4337'],
  },

  // ── Gas & Fee Standards ──
  {
    id: 'eip-1559',
    category: 'eip',
    number: '1559',
    name: 'EIP-1559: Fee Market Change',
    description: 'Redesigned Ethereum transaction fee mechanism with base fee burning and priority tips. Creates deflationary pressure on ETH. All platform transactions use EIP-1559 type-2 transactions for predictable gas costs.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1559',
    applicableTo: ['All transactions', 'Gas estimation', 'Fee prediction'],
    requiredForCompliance: true,
    relatedStandards: ['erc-20', 'erc-721'],
  },

  // ── Proxy & Upgradeability ──
  {
    id: 'eip-1967',
    category: 'eip',
    number: '1967',
    name: 'EIP-1967: Proxy Storage Slots',
    description: 'Standardizes storage slot locations for proxy contracts — implementation address, admin address, and beacon address. Prevents storage collisions between proxy and implementation. Used by OpenZeppelin\'s transparent and UUPS proxies.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1967',
    applicableTo: ['Upgradeable contracts', 'Proxy patterns', 'UUPS'],
    requiredForCompliance: false,
    relatedStandards: ['eip-1822', 'oz-proxy'],
  },
  {
    id: 'eip-1822',
    category: 'eip',
    number: '1822',
    name: 'EIP-1822: UUPS (Universal Upgradeable Proxy)',
    description: 'Universal Upgradeable Proxy Standard. Places upgrade logic in the implementation contract rather than the proxy, reducing gas costs. OpenZeppelin\'s recommended upgrade pattern for new deployments.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1822',
    applicableTo: ['Upgradeable tokens', 'Protocol evolution'],
    requiredForCompliance: false,
    relatedStandards: ['eip-1967', 'oz-proxy'],
  },
  {
    id: 'eip-1167',
    category: 'eip',
    number: '1167',
    name: 'EIP-1167: Minimal Proxy (Clone)',
    description: 'Specifies a minimal bytecode implementation that delegates all calls to a known, fixed address. Enables cheap deployment of many identical contract instances. Used for factory patterns (e.g., creating user vaults, clone strategies).',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1167',
    applicableTo: ['Clone factories', 'Vault deployment', 'Strategy clones'],
    requiredForCompliance: false,
    relatedStandards: ['eip-1967', 'oz-proxy'],
  },

  // ── Account Abstraction ──
  {
    id: 'eip-4337',
    category: 'eip',
    number: '4337',
    name: 'EIP-4337: Account Abstraction (UserOperations)',
    description: 'Enables smart contract wallets as first-class accounts without protocol changes. Supports gasless transactions, batch operations, social recovery, and session keys. Foundation for next-gen wallet UX.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-4337',
    applicableTo: ['Smart wallets', 'Gasless UX', 'Social recovery', 'Session keys'],
    requiredForCompliance: false,
    relatedStandards: ['eip-1271', 'eip-7702'],
  },
  {
    id: 'eip-7702',
    category: 'eip',
    number: '7702',
    name: 'EIP-7702: EOA Code Delegation',
    description: 'Allows externally-owned accounts to temporarily delegate to smart contract code within a transaction. Bridges EOA and smart account worlds. Included in Ethereum\'s Pectra upgrade.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-7702',
    applicableTo: ['Account abstraction', 'EOA upgrades', 'Batch transactions'],
    requiredForCompliance: false,
    relatedStandards: ['eip-4337'],
  },

  // ── Token Extensions ──
  {
    id: 'eip-2309',
    category: 'eip',
    number: '2309',
    name: 'EIP-2309: Consecutive Transfer Extension',
    description: 'Defines a ConsecutiveTransfer event for efficient batch minting/transferring of NFTs. Emits a single event for a range of token IDs instead of individual Transfer events. Used by ERC-721A and OpenZeppelin ERC721Consecutive.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-2309',
    applicableTo: ['Batch minting', 'NFT collections', 'Gas optimization'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'erc-721a'],
  },
  {
    id: 'erc-777',
    category: 'erc',
    number: '777',
    name: 'ERC-777: Advanced Token Standard',
    description: 'Advanced fungible token standard with operator permissions and send/receive hooks. Backwards-compatible with ERC-20. Superseded in most new projects by ERC-20 + ERC-2612, but relevant for understanding the token standard evolution.',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-777',
    applicableTo: ['Legacy token support', 'Operator permissions'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-2612'],
  },
  {
    id: 'erc-1363',
    category: 'erc',
    number: '1363',
    name: 'ERC-1363: Payable Token',
    description: 'Extension allowing ERC-20 tokens to execute receiver/spender callbacks in a single transaction. Enables "transfer and call" patterns — pay with tokens and trigger contract logic atomically. Useful for subscription payments and marketplace purchases.',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-1363',
    applicableTo: ['Token payments', 'Subscriptions', 'Marketplace'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-2612'],
  },
  {
    id: 'erc-2135',
    category: 'erc',
    number: '2135',
    name: 'ERC-2135: Consumable Interface (Tickets)',
    description: 'Standard interface for consumable tokens — items that can be "used up" like tickets, vouchers, or access passes. Tracks consumption state. Applicable to futures vouchers and reward redemptions on the platform.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-2135',
    applicableTo: ['Futures vouchers', 'Reward redemptions', 'Event tickets', 'Access passes'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'erc-1155'],
  },
];
