/**
 * OpenZeppelin Contract Library Standards
 * Industry-standard audited smart contract implementations
 * https://www.openzeppelin.com/ | https://github.com/OpenZeppelin
 */

import type { ProtocolStandard } from './protocolRegistry';

export const OPENZEPPELIN_STANDARDS: ProtocolStandard[] = [
  // ── Core Libraries ──
  {
    id: 'oz-contracts-5',
    category: 'erc',
    number: 'OZ 5.x',
    name: 'OpenZeppelin Contracts v5.x',
    description: 'Industry-standard library of audited, reusable Solidity smart contracts. Implements ERC-20, ERC-721, ERC-1155, access control, governance, and security primitives. All platform contracts MUST inherit from OpenZeppelin base implementations.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/',
    applicableTo: ['All smart contracts', 'Token deployment', 'Access control', 'Governance'],
    requiredForCompliance: true,
    relatedStandards: ['erc-20', 'erc-721', 'erc-1155', 'erc-1400'],
  },
  {
    id: 'oz-erc20',
    category: 'erc',
    number: 'OZ-ERC20',
    name: 'OZ ERC20: Fungible Token Implementation',
    description: 'OpenZeppelin\'s audited ERC-20 implementation with extensions: Burnable (deflationary supply), Pausable (emergency halt), Permit (gasless approvals via ERC-2612), Votes (governance snapshots), FlashMint (flash loans), and Capped (max supply enforcement).',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/erc20',
    applicableTo: ['$QTC', '$QAQI', '$AIQTP', 'All fungible tokens'],
    requiredForCompliance: true,
    relatedStandards: ['erc-20', 'erc-2612', 'oz-contracts-5'],
  },
  {
    id: 'oz-erc721',
    category: 'erc',
    number: 'OZ-ERC721',
    name: 'OZ ERC721: NFT Implementation',
    description: 'OpenZeppelin\'s audited ERC-721 implementation with extensions: Enumerable (on-chain token listing), URIStorage (per-token metadata), Burnable, Pausable, Royalty (EIP-2981), Consecutive (batch mint via EIP-2309), and Wrapper.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/erc721',
    applicableTo: ['NFT collections', 'Bot Persona Cards', 'Unique assets'],
    requiredForCompliance: true,
    relatedStandards: ['erc-721', 'eip-2981', 'oz-contracts-5'],
  },
  {
    id: 'oz-erc1155',
    category: 'erc',
    number: 'OZ-ERC1155',
    name: 'OZ ERC1155: Multi-Token Implementation',
    description: 'OpenZeppelin\'s audited ERC-1155 implementation supporting both fungible and non-fungible tokens in a single contract. Extensions: Burnable, Pausable, Supply (track per-ID totals), and URIStorage.',
    assetClassification: 'semi_fungible',
    valueNature: 'hybrid',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/erc1155',
    applicableTo: ['Edition NFTs', 'Gaming items', 'Mixed collections'],
    requiredForCompliance: true,
    relatedStandards: ['erc-1155', 'oz-contracts-5'],
  },

  // ── Security Primitives ──
  {
    id: 'oz-access-control',
    category: 'erc',
    number: 'OZ-Access',
    name: 'OZ AccessControl: Role-Based Permissions',
    description: 'Flexible role-based access control with hierarchical admin roles. Supports Ownable (single owner), AccessControl (role-based), AccessManaged (authority delegation), and Governor (on-chain governance). Critical for contract administration.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/access-control',
    applicableTo: ['Contract administration', 'Multi-sig', 'DAO governance'],
    requiredForCompliance: true,
    relatedStandards: ['oz-contracts-5'],
  },
  {
    id: 'oz-security',
    category: 'erc',
    number: 'OZ-Security',
    name: 'OZ Security: ReentrancyGuard & Pausable',
    description: 'Battle-tested security primitives: ReentrancyGuard (prevents re-entrancy attacks), Pausable (emergency circuit breaker), PullPayment (safe withdrawal pattern). Every platform contract MUST use ReentrancyGuard on state-changing external calls.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/api/utils#ReentrancyGuard',
    applicableTo: ['All contracts', 'DeFi', 'Payments', 'Minting'],
    requiredForCompliance: true,
    relatedStandards: ['oz-contracts-5'],
  },
  {
    id: 'oz-proxy',
    category: 'erc',
    number: 'OZ-Proxy',
    name: 'OZ Proxy: Upgradeable Contracts (UUPS/Transparent)',
    description: 'OpenZeppelin\'s proxy patterns for upgradeable smart contracts. UUPS (Universal Upgradeable Proxy Standard, ERC-1822) and TransparentUpgradeableProxy. Allows contract logic upgrades without losing state or changing addresses.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/api/proxy',
    applicableTo: ['Upgradeable tokens', 'Protocol upgrades', 'Long-lived contracts'],
    requiredForCompliance: false,
    relatedStandards: ['oz-contracts-5'],
  },
  {
    id: 'oz-governance',
    category: 'erc',
    number: 'OZ-Gov',
    name: 'OZ Governor: On-Chain Governance',
    description: 'Modular governance framework compatible with Compound\'s Governor Bravo. Supports proposal creation, voting (simple/weighted/quorum), timelock execution, and token-based voting power (ERC20Votes, ERC721Votes).',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://docs.openzeppelin.com/contracts/5.x/governance',
    applicableTo: ['DAO governance', '$QTC voting', 'Protocol decisions'],
    requiredForCompliance: false,
    relatedStandards: ['oz-contracts-5', 'erc-20'],
  },
];
