/**
 * NIST CSRC Post-Quantum Cryptography Standards
 * https://csrc.nist.gov/projects/post-quantum-cryptography
 * https://www.nist.gov/pqc
 */

import type { ProtocolStandard } from './protocolRegistry';

export const PQC_STANDARDS: ProtocolStandard[] = [
  // ── NIST PQC Project Overview ──
  {
    id: 'nist-pqc-project',
    category: 'nist',
    number: 'PQC',
    name: 'NIST PQC: Post-Quantum Cryptography Project',
    description: 'NIST\'s multi-year initiative to standardize quantum-resistant cryptographic algorithms. Began in 2016, finalized first standards in August 2024 (FIPS 203, 204, 205). Ensures all cryptographic operations remain secure against both classical and quantum computing attacks. The platform adheres to all finalized PQC standards.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    applicableTo: ['All cryptographic operations', 'Key exchange', 'Digital signatures', 'Wallet security'],
    requiredForCompliance: true,
    relatedStandards: ['fips-203', 'fips-204', 'fips-205', 'fips-206', 'nist-csrc-pqc-migration'],
  },

  // ── CSRC Specific Guidelines ──
  {
    id: 'nist-csrc-pqc-migration',
    category: 'nist',
    number: 'CSRC-PQC-MIG',
    name: 'NIST CSRC: PQC Migration Guidelines',
    description: 'NIST Computer Security Resource Center guidance for migrating from classical to post-quantum cryptography. Defines hybrid approaches (classical + PQC) during transition period, key management updates, and algorithm agility requirements. Platform implements hybrid mode: secp256k1 (classical) + ML-KEM-768 (quantum-safe) for key exchange.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    applicableTo: ['Cryptographic migration', 'Hybrid encryption', 'Key management'],
    requiredForCompliance: true,
    relatedStandards: ['nist-pqc-project', 'fips-203', 'fips-204'],
  },
  {
    id: 'nist-sp-800-227',
    category: 'nist',
    number: 'SP 800-227',
    name: 'NIST SP 800-227: PQC Migration Recommendations',
    description: 'Initial Public Draft providing recommendations for migrating to post-quantum cryptographic standards. Covers inventory of quantum-vulnerable systems, prioritization of migration efforts, and timeline for deprecating pre-quantum algorithms.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'draft',
    url: 'https://csrc.nist.gov/pubs/sp/800/227/ipd',
    applicableTo: ['Migration planning', 'System inventory', 'Algorithm deprecation'],
    requiredForCompliance: false,
    relatedStandards: ['nist-pqc-project', 'nist-csrc-pqc-migration'],
  },

  // ── Lattice-Based Standards (Primary) ──
  {
    id: 'pqc-ml-kem-512',
    category: 'nist',
    number: 'ML-KEM-512',
    name: 'ML-KEM-512 (Kyber-512): Lightweight Key Encapsulation',
    description: 'NIST security level 1 variant of ML-KEM. Smallest key sizes and fastest performance. Suitable for resource-constrained environments like mobile wallets and IoT devices. 128-bit equivalent quantum security.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/203/final',
    applicableTo: ['Mobile wallets', 'IoT devices', 'Lightweight channels'],
    requiredForCompliance: false,
    relatedStandards: ['fips-203', 'pqc-ml-kem-768', 'pqc-ml-kem-1024'],
  },
  {
    id: 'pqc-ml-kem-768',
    category: 'nist',
    number: 'ML-KEM-768',
    name: 'ML-KEM-768 (Kyber-768): Standard Key Encapsulation',
    description: 'NIST security level 3 variant of ML-KEM. Recommended default for most applications. Balances security and performance. 192-bit equivalent quantum security. This is the platform\'s PRIMARY key encapsulation mechanism for all wallet and channel encryption.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/203/final',
    applicableTo: ['Primary wallet encryption', 'Key exchange', 'All secure channels'],
    requiredForCompliance: true,
    relatedStandards: ['fips-203', 'pqc-ml-kem-512', 'pqc-ml-kem-1024'],
  },
  {
    id: 'pqc-ml-kem-1024',
    category: 'nist',
    number: 'ML-KEM-1024',
    name: 'ML-KEM-1024 (Kyber-1024): High-Security Key Encapsulation',
    description: 'NIST security level 5 variant of ML-KEM. Maximum security for protecting long-lived secrets and highest-value assets. 256-bit equivalent quantum security. Used for treasury wallet master keys and admin key exchange.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/203/final',
    applicableTo: ['Treasury wallets', 'Admin keys', 'Long-term secrets'],
    requiredForCompliance: false,
    relatedStandards: ['fips-203', 'pqc-ml-kem-768'],
  },

  // ── Signature Variants ──
  {
    id: 'pqc-ml-dsa-44',
    category: 'nist',
    number: 'ML-DSA-44',
    name: 'ML-DSA-44 (Dilithium-2): Lightweight Signatures',
    description: 'NIST security level 2 variant of ML-DSA. Smallest signatures in the ML-DSA family. Used for high-frequency transaction signing where speed matters. 128-bit equivalent quantum security.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/204/final',
    applicableTo: ['High-frequency trading', 'Micro-transactions', 'Bot signatures'],
    requiredForCompliance: false,
    relatedStandards: ['fips-204', 'pqc-ml-dsa-65', 'pqc-ml-dsa-87'],
  },
  {
    id: 'pqc-ml-dsa-65',
    category: 'nist',
    number: 'ML-DSA-65',
    name: 'ML-DSA-65 (Dilithium-3): Standard Signatures',
    description: 'NIST security level 3 variant of ML-DSA. Recommended default for transaction signing. Platform PRIMARY signature algorithm for all user transactions, contract deployments, and identity attestations. 192-bit equivalent quantum security.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/204/final',
    applicableTo: ['All transaction signing', 'Contract deployment', 'Identity verification'],
    requiredForCompliance: true,
    relatedStandards: ['fips-204', 'pqc-ml-dsa-44', 'pqc-ml-dsa-87'],
  },
  {
    id: 'pqc-ml-dsa-87',
    category: 'nist',
    number: 'ML-DSA-87',
    name: 'ML-DSA-87 (Dilithium-5): High-Security Signatures',
    description: 'NIST security level 5 variant of ML-DSA. Maximum security for admin operations and irreversible actions. 256-bit equivalent quantum security. Used for treasury operations and governance votes.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/204/final',
    applicableTo: ['Treasury operations', 'Admin actions', 'Governance'],
    requiredForCompliance: false,
    relatedStandards: ['fips-204', 'pqc-ml-dsa-65'],
  },

  // ── Hash-Based (Backup / Diversity) ──
  {
    id: 'pqc-slh-dsa-shake-256f',
    category: 'nist',
    number: 'SLH-DSA-256f',
    name: 'SLH-DSA-SHAKE-256f (SPHINCS+-256f): Fast Hash Signatures',
    description: 'Fastest variant of SLH-DSA (SPHINCS+) at security level 5. Provides algorithm diversity — based on hash functions rather than lattices, so a lattice breakthrough would not compromise these signatures. Used as backup/fallback signing.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://csrc.nist.gov/pubs/fips/205/final',
    applicableTo: ['Backup signatures', 'Algorithm diversity', 'Long-term verification'],
    requiredForCompliance: false,
    relatedStandards: ['fips-205', 'pqc-ml-dsa-65'],
  },

  // ── Additional Round Candidates ──
  {
    id: 'pqc-hqc',
    category: 'nist',
    number: 'HQC',
    name: 'HQC: Hamming Quasi-Cyclic KEM',
    description: 'Selected in NIST PQC Round 4 as backup KEM based on code-based cryptography (not lattices). Provides algorithm diversity for key encapsulation. Expected standardization as future FIPS. Platform monitors for inclusion.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'draft',
    url: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    applicableTo: ['Future backup KEM', 'Algorithm diversity'],
    requiredForCompliance: false,
    relatedStandards: ['fips-203', 'nist-pqc-project'],
  },
  {
    id: 'pqc-bike',
    category: 'nist',
    number: 'BIKE',
    name: 'BIKE: Bit Flipping Key Encapsulation',
    description: 'NIST PQC Round 4 candidate. Code-based KEM with compact keys. Under evaluation for potential standardization as additional algorithm diversity beyond lattice-based ML-KEM.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'draft',
    url: 'https://csrc.nist.gov/projects/post-quantum-cryptography',
    applicableTo: ['Future backup KEM', 'Compact key environments'],
    requiredForCompliance: false,
    relatedStandards: ['fips-203', 'pqc-hqc'],
  },
];
