/**
 * RWA, DeFi, Regulatory & Emerging Standards
 * Real-World Asset tokenization, financial regulation, and next-gen ERC standards
 */

import type { ProtocolStandard } from './protocolRegistry';

export const RWA_EMERGING_STANDARDS: ProtocolStandard[] = [
  // ═══════════════════════════════════════
  //  RWA & FINANCIAL INSTRUMENT TOKENS
  // ═══════════════════════════════════════
  {
    id: 'erc-3525',
    category: 'erc',
    number: '3525',
    name: 'ERC-3525: Semi-Fungible Token (SFT)',
    description: 'Combines ERC-20 fungibility with ERC-721 uniqueness via "slots". Tokens in the same slot are fungible; across slots they are unique. Purpose-built for financial instruments — bonds, insurance policies, vesting schedules, and structured RWA products.',
    assetClassification: 'semi_fungible',
    valueNature: 'hybrid',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-3525',
    applicableTo: ['Bonds', 'Insurance', 'Vesting schedules', 'Structured products', 'RWA tranches'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-721', 'erc-1155', 'erc-3643'],
  },
  {
    id: 'erc-6960',
    category: 'erc',
    number: '6960',
    name: 'ERC-6960: Dual-Layer Token',
    description: 'Two-tier token model with a "main ID" and "sub ID" enabling fractional ownership of unique assets. Designed explicitly for RWA fractionalization — a property (mainId) can have thousands of fractional shares (subId), each tradeable.',
    assetClassification: 'real_world_asset',
    valueNature: 'hybrid',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-6960',
    applicableTo: ['Fractional real estate', 'RWA fractionalization', 'Tokenized funds', 'Commodity shares'],
    requiredForCompliance: false,
    relatedStandards: ['erc-1155', 'erc-3525', 'erc-3643'],
  },
  {
    id: 'erc-4519',
    category: 'erc',
    number: '4519',
    name: 'ERC-4519: Physical Asset NFT',
    description: 'Standard for binding NFTs to physical, real-world assets with ownership and user roles. Supports owner/user separation and on-chain proof of physical asset custody. Critical for IoT-linked RWA like vehicles, machinery, or art.',
    assetClassification: 'real_world_asset',
    valueNature: 'like_but_not_similar',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-4519',
    applicableTo: ['Physical asset tracking', 'IoT-linked NFTs', 'Vehicle titles', 'Art provenance'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'erc-3643', 'erc-6960'],
  },

  // ═══════════════════════════════════════
  //  TOKEN ARCHITECTURE & COMPOSABILITY
  // ═══════════════════════════════════════
  {
    id: 'erc-6551',
    category: 'erc',
    number: '6551',
    name: 'ERC-6551: Token Bound Accounts (TBA)',
    description: 'Every NFT gets its own smart contract wallet. Enables NFTs to own other assets, interact with dApps, and accumulate history. Transforms NFTs from static images into autonomous on-chain identities. Essential for bot persona cards that hold strategies and earnings.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-6551',
    applicableTo: ['Bot Persona Cards', 'NFT wallets', 'On-chain identity', 'Composable NFTs'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'eip-4337', 'erc-1155'],
  },
  {
    id: 'erc-7401',
    category: 'erc',
    number: '7401',
    name: 'ERC-7401: Nestable NFT',
    description: 'Allows NFTs to own other NFTs in a parent-child hierarchy. Enables composable asset bundles — e.g., a portfolio NFT containing multiple strategy NFTs, or a property NFT bundling deed + inspection + insurance NFTs.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-7401',
    applicableTo: ['Portfolio bundles', 'Composable assets', 'Nested collections', 'RWA document bundles'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'erc-6551', 'erc-5773'],
  },
  {
    id: 'erc-5773',
    category: 'erc',
    number: '5773',
    name: 'ERC-5773: Multi-Asset NFT',
    description: 'Allows a single NFT to hold multiple asset types (images, 3D models, documents, audio). Context-dependent rendering — the same NFT shows as an image on OpenSea, a 3D model in a metaverse, and a PDF in a document viewer.',
    assetClassification: 'non_fungible_unique',
    valueNature: 'like_but_not_similar',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-5773',
    applicableTo: ['Multi-format NFTs', 'Cross-platform assets', 'RWA with documents'],
    requiredForCompliance: false,
    relatedStandards: ['erc-721', 'erc-7401'],
  },
  {
    id: 'erc-2535',
    category: 'erc',
    number: '2535',
    name: 'ERC-2535: Diamond Standard (Multi-Facet Proxy)',
    description: 'Allows a single contract address to support unlimited function selectors via "facets". Overcomes the 24KB contract size limit. Enables modular, upgradeable contract systems where each facet handles a domain (trading, staking, governance).',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-2535',
    applicableTo: ['Complex protocol contracts', 'Modular systems', 'Upgradeable architecture'],
    requiredForCompliance: false,
    relatedStandards: ['eip-1967', 'eip-1822', 'eip-1167'],
  },

  // ═══════════════════════════════════════
  //  DeFi STANDARDS
  // ═══════════════════════════════════════
  {
    id: 'erc-3156',
    category: 'erc',
    number: '3156',
    name: 'ERC-3156: Flash Loan Standard',
    description: 'Standardized interface for flash loans — uncollateralized loans that must be repaid within a single transaction. Enables arbitrage, liquidations, and collateral swaps. The lender and borrower interfaces ensure cross-protocol compatibility.',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-3156',
    applicableTo: ['Flash loans', 'Arbitrage', 'Liquidations', 'DeFi composability'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-4626'],
  },
  {
    id: 'erc-7540',
    category: 'erc',
    number: '7540',
    name: 'ERC-7540: Asynchronous Tokenized Vault',
    description: 'Extension of ERC-4626 supporting asynchronous deposit/redemption flows. Crucial for RWA vaults where settlement isn\'t instant — real estate funds, private credit, and institutional products requiring KYC/AML checks before processing.',
    assetClassification: 'real_world_asset',
    valueNature: 'hybrid',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-7540',
    applicableTo: ['RWA vaults', 'Private credit', 'Institutional funds', 'Delayed settlement'],
    requiredForCompliance: false,
    relatedStandards: ['erc-4626', 'erc-3643', 'erc-6960'],
  },
  {
    id: 'erc-7621',
    category: 'erc',
    number: '7621',
    name: 'ERC-7621: Basket Token',
    description: 'Standard for tokens that represent a weighted basket of underlying ERC-20 tokens. Enables on-chain index funds, ETF-like products, and diversified portfolio tokens. Supports rebalancing and fee mechanisms.',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-7621',
    applicableTo: ['Index funds', 'ETF tokens', 'Basket tokens', 'Diversified portfolios'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-4626'],
  },

  // ═══════════════════════════════════════
  //  IDENTITY & ATTESTATION
  // ═══════════════════════════════════════
  {
    id: 'erc-7231',
    category: 'erc',
    number: '7231',
    name: 'ERC-7231: Identity-Aggregated NFT',
    description: 'Binds multiple Web2/Web3 identities to a single NFT — social accounts, wallet addresses, and KYC attestations. Creates a unified on-chain identity layer. Essential for RWA compliance where asset holders must be verified across jurisdictions.',
    assetClassification: 'soulbound',
    valueNature: 'like_but_not_similar',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-7231',
    applicableTo: ['KYC aggregation', 'Cross-chain identity', 'RWA holder verification'],
    requiredForCompliance: false,
    relatedStandards: ['erc-5192', 'erc-3643', 'erc-721'],
  },
  {
    id: 'erc-735',
    category: 'erc',
    number: '735',
    name: 'ERC-735: Claim Holder (Identity Claims)',
    description: 'Standard for managing identity claims — attestations about an address issued by trusted third parties. Supports KYC/AML claims, accredited investor status, and jurisdiction verification. Foundational for ERC-3643 T-REX compliance.',
    assetClassification: 'soulbound',
    valueNature: 'regulatory',
    status: 'draft',
    url: 'https://github.com/ethereum/EIPs/issues/735',
    applicableTo: ['KYC claims', 'Accredited investor status', 'Identity verification', 'RWA compliance'],
    requiredForCompliance: false,
    relatedStandards: ['erc-3643', 'erc-725', 'erc-5192'],
  },
  {
    id: 'erc-725',
    category: 'erc',
    number: '725',
    name: 'ERC-725: Proxy Account (On-Chain Identity)',
    description: 'Smart contract-based identity that can hold keys and execute actions. The on-chain identity contract used by ERC-3643 (T-REX) for RWA compliance. Supports key management with different permission levels (management, action, claim, encryption).',
    assetClassification: 'soulbound',
    valueNature: 'regulatory',
    status: 'draft',
    url: 'https://eips.ethereum.org/EIPS/eip-725',
    applicableTo: ['On-chain identity', 'Key management', 'RWA identity layer', 'T-REX identity'],
    requiredForCompliance: false,
    relatedStandards: ['erc-735', 'erc-3643', 'eip-4337'],
  },

  // ═══════════════════════════════════════
  //  FINANCIAL REGULATORY STANDARDS
  // ═══════════════════════════════════════
  {
    id: 'iso-10962',
    category: 'iso',
    number: '10962',
    name: 'ISO 10962: CFI — Classification of Financial Instruments',
    description: 'International standard for classifying financial instruments with a 6-character code. Categorizes equities, debt, derivatives, collective investments, and structured products. Required for tokenized securities to be recognized by traditional financial infrastructure.',
    assetClassification: 'security_token',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://www.iso.org/standard/81140.html',
    applicableTo: ['Tokenized securities', 'Security token classification', 'Regulatory reporting'],
    requiredForCompliance: true,
    relatedStandards: ['iso-6166', 'erc-1400', 'erc-3643'],
  },
  {
    id: 'iso-6166',
    category: 'iso',
    number: '6166',
    name: 'ISO 6166: ISIN — International Securities Identification',
    description: 'Defines the International Securities Identification Number (ISIN), a 12-character alphanumeric code uniquely identifying securities globally. Tokenized RWAs seeking institutional adoption require ISIN assignment for cross-border trading and settlement.',
    assetClassification: 'security_token',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://www.iso.org/standard/78502.html',
    applicableTo: ['Tokenized securities', 'Cross-border trading', 'Institutional settlement'],
    requiredForCompliance: true,
    relatedStandards: ['iso-10962', 'iso-24165', 'erc-1400'],
  },
  {
    id: 'mica-regulation',
    category: 'iso',
    number: 'MiCA',
    name: 'MiCA: EU Markets in Crypto-Assets Regulation',
    description: 'European Union regulatory framework for crypto-assets effective June 2024. Classifies tokens as ARTs (Asset-Referenced Tokens), EMTs (E-Money Tokens), or utility tokens. Mandates whitepaper requirements, reserve backing, and authorized CASP licensing for EU operations.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica',
    applicableTo: ['EU-listed tokens', 'Stablecoins', 'Exchange operations', 'Token offerings'],
    requiredForCompliance: true,
    relatedStandards: ['fatf-travel-rule', 'erc-3643', 'iso-24165'],
  },
  {
    id: 'fatf-travel-rule',
    category: 'iso',
    number: 'FATF-R16',
    name: 'FATF Travel Rule (Recommendation 16)',
    description: 'Financial Action Task Force requirement that VASPs (Virtual Asset Service Providers) must share originator and beneficiary information for transfers above threshold. Anti-money-laundering standard applicable to all crypto exchanges and custodians on the platform.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'active',
    url: 'https://www.fatf-gafi.org/en/publications/Fatfrecommendations/R16-trwg-update.html',
    applicableTo: ['Exchange transfers', 'Cross-border crypto', 'AML compliance', 'Custodial services'],
    requiredForCompliance: true,
    relatedStandards: ['mica-regulation', 'erc-3643'],
  },
  {
    id: 'erc-6093',
    category: 'erc',
    number: '6093',
    name: 'ERC-6093: Custom Errors for Common Tokens',
    description: 'Standardizes custom Solidity error types for ERC-20, ERC-721, and ERC-1155 tokens. Replaces string revert messages with structured errors, reducing gas costs and improving developer UX. Adopted by OpenZeppelin Contracts v5.',
    assetClassification: 'fungible_currency',
    valueNature: 'regulatory',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-6093',
    applicableTo: ['All token contracts', 'Error handling', 'Gas optimization'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-721', 'erc-1155', 'oz-contracts-v5'],
  },
  {
    id: 'erc-7528',
    category: 'erc',
    number: '7528',
    name: 'ERC-7528: ETH (Native Asset) Address Convention',
    description: 'Establishes 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE as the canonical address representing native ETH in smart contracts. Eliminates ambiguity in DeFi protocols that handle both ERC-20 tokens and native ETH, reducing integration bugs.',
    assetClassification: 'fungible_currency',
    valueNature: 'like_and_similar',
    status: 'final',
    url: 'https://eips.ethereum.org/EIPS/eip-7528',
    applicableTo: ['DeFi protocols', 'DEX routing', 'Payment processing', 'Multi-asset contracts'],
    requiredForCompliance: false,
    relatedStandards: ['erc-20', 'erc-4626'],
  },
];