import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import {
  Store,
  Globe,
  Rocket,
  CheckCircle2,
  Clock,
  ExternalLink,
  Bot,
  Loader2,
} from "lucide-react";

interface StoreTarget {
  id: string;
  name: string;
  category: "pwa" | "directory" | "native";
  status: "pending" | "submitted" | "live" | "rejected";
  url?: string;
  estimatedTime: string;
  icon: string;
}

const StoreListingAutomation = () => {
  const [stores, setStores] = useState<StoreTarget[]>([
    { id: "pwa-google", name: "Google Play (PWA/TWA)", category: "pwa", status: "pending", estimatedTime: "3-5 days", icon: "🤖" },
    { id: "pwa-microsoft", name: "Microsoft Store (PWA)", category: "pwa", status: "pending", estimatedTime: "1-2 days", icon: "🪟" },
    { id: "product-hunt", name: "Product Hunt", category: "directory", status: "pending", estimatedTime: "1 day", icon: "🚀" },
    { id: "alternativeto", name: "AlternativeTo", category: "directory", status: "pending", estimatedTime: "1-3 days", icon: "🔄" },
    { id: "g2", name: "G2", category: "directory", status: "pending", estimatedTime: "3-7 days", icon: "⭐" },
    { id: "capterra", name: "Capterra", category: "directory", status: "pending", estimatedTime: "5-10 days", icon: "📊" },
    { id: "saashub", name: "SaaSHub", category: "directory", status: "pending", estimatedTime: "1-2 days", icon: "🔌" },
    { id: "betalist", name: "BetaList", category: "directory", status: "pending", estimatedTime: "1-3 days", icon: "🧪" },
  ]);

  const [generating, setGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<string | null>(null);

  const handleGenerateListings = async () => {
    setGenerating(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        toast.error("Please sign in to use QuantClaw automation");
        return;
      }

      const res = await supabase.functions.invoke("quantclaw-marketing", {
        body: {
          action: "generate_content",
          platform: "app_directory",
          topic: "AIQTP platform listing - AI Quantum Trading Platform with $QTC token, autonomous agents, NFT studio, DeFi tools. Generate: app title, short description (80 chars), long description (4000 chars), feature bullets, keywords, and category suggestions for app store and web directory submission.",
          tone: "professional",
        },
      });

      if (res.error) throw res.error;
      setGeneratedContent(res.data?.content || "Content generated successfully");
      toast.success("Store listing content generated by QuantClaw!");
    } catch (err: any) {
      toast.error(err.message || "Failed to generate listing content");
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = (storeId: string) => {
    setStores((prev) =>
      prev.map((s) =>
        s.id === storeId ? { ...s, status: "submitted" as const } : s
      )
    );
    toast.success(`Submission initiated for ${stores.find((s) => s.id === storeId)?.name}`);
  };

  const statusColor = (status: string) => {
    switch (status) {
      case "live": return "border-green-500 text-green-500";
      case "submitted": return "border-yellow-500 text-yellow-500";
      case "rejected": return "border-destructive text-destructive";
      default: return "border-muted-foreground text-muted-foreground";
    }
  };

  const statusIcon = (status: string) => {
    switch (status) {
      case "live": return <CheckCircle2 className="h-3 w-3" />;
      case "submitted": return <Clock className="h-3 w-3" />;
      default: return null;
    }
  };

  const liveCount = stores.filter((s) => s.status === "live").length;
  const submittedCount = stores.filter((s) => s.status === "submitted").length;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            <Store className="h-6 w-6 text-primary" />
            App Store &amp; Directory Listings
          </h2>
          <p className="text-muted-foreground">
            QuantClaw automates listing submissions to maximize distribution
          </p>
        </div>
        <div className="flex gap-2">
          <Badge variant="secondary">{liveCount} Live</Badge>
          <Badge variant="outline">{submittedCount} Pending</Badge>
        </div>
      </div>

      {/* Auto-generate button */}
      <Card className="bg-primary/5 border-primary/20">
        <CardContent className="p-4 flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-3">
            <Bot className="h-8 w-8 text-primary" />
            <div>
              <h4 className="font-semibold">QuantClaw™ Auto-Generate</h4>
              <p className="text-sm text-muted-foreground">
                AI generates optimized listing copy for all stores at once
              </p>
            </div>
          </div>
          <Button onClick={handleGenerateListings} disabled={generating}>
            {generating ? (
              <><Loader2 className="h-4 w-4 mr-1 animate-spin" /> Generating…</>
            ) : (
              <><Rocket className="h-4 w-4 mr-1" /> Generate All Listings</>
            )}
          </Button>
        </CardContent>
      </Card>

      {generatedContent && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">Generated Listing Content</CardTitle>
          </CardHeader>
          <CardContent>
            <pre className="text-xs text-muted-foreground whitespace-pre-wrap max-h-60 overflow-auto bg-secondary/50 p-3 rounded-md">
              {generatedContent}
            </pre>
          </CardContent>
        </Card>
      )}

      {/* Store targets */}
      <div className="space-y-3">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <Globe className="h-5 w-5" />
          PWA Stores
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {stores.filter((s) => s.category === "pwa").map((store) => (
            <Card key={store.id}>
              <CardContent className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <span className="text-2xl">{store.icon}</span>
                  <div>
                    <h4 className="font-medium text-sm">{store.name}</h4>
                    <span className="text-xs text-muted-foreground">
                      ETA: {store.estimatedTime}
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className={statusColor(store.status)}>
                    {statusIcon(store.status)}
                    <span className="ml-1 capitalize">{store.status}</span>
                  </Badge>
                  {store.status === "pending" && (
                    <Button size="sm" variant="outline" onClick={() => handleSubmit(store.id)}>
                      Submit
                    </Button>
                  )}
                  {store.status === "live" && store.url && (
                    <Button size="sm" variant="ghost" asChild>
                      <a href={store.url} target="_blank" rel="noopener noreferrer">
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <h3 className="text-lg font-semibold flex items-center gap-2 mt-4">
          <Rocket className="h-5 w-5" />
          Web Directories
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {stores.filter((s) => s.category === "directory").map((store) => (
            <Card key={store.id}>
              <CardContent className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <span className="text-2xl">{store.icon}</span>
                  <div>
                    <h4 className="font-medium text-sm">{store.name}</h4>
                    <span className="text-xs text-muted-foreground">
                      ETA: {store.estimatedTime}
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className={statusColor(store.status)}>
                    {statusIcon(store.status)}
                    <span className="ml-1 capitalize">{store.status}</span>
                  </Badge>
                  {store.status === "pending" && (
                    <Button size="sm" variant="outline" onClick={() => handleSubmit(store.id)}>
                      Submit
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};

export default StoreListingAutomation;
